import { ThemeCodeType } from "../interfaces";

const themeBgColorMap: ThemeCodeType = {
  "light-red": {
    primary: "bg-light-red-primary",
    secondary: "bg-light-red-tertiary",
    tertiary: "bg-light-red-tertiary",
    quaternary: "bg-light-red-quaternary",
    quinary: "bg-light-red-quinary",
    active: {
      primary: "active:bg-light-red-primary",
      secondary: "active:bg-light-red-tertiary",
      tertiary: "active:bg-light-red-tertiary",
      quaternary: "active:bg-light-red-quaternary",
      quinary: "active:bg-light-red-quinary",
    },
    focus: {
      primary: "focus:bg-light-red-primary",
      secondary: "focus:bg-light-red-tertiary",
      tertiary: "focus:bg-light-red-tertiary",
      quaternary: "focus:bg-light-red-quaternary",
      quinary: "focus:bg-light-red-quinary",
    },
    hover: {
      primary: "hover:bg-light-red-primary",
      secondary: "hover:bg-light-red-tertiary",
      tertiary: "hover:bg-light-red-tertiary",
      quaternary: "hover:bg-light-red-quaternary",
      quinary: "hover:bg-light-red-quinary",
    },
  },
  "light-green": {
    primary: "bg-light-green-primary",
    secondary: "bg-light-green-tertiary",
    tertiary: "bg-light-green-tertiary",
    quaternary: "bg-light-green-quaternary",
    quinary: "bg-light-green-quinary",
    active: {
      primary: "active:bg-light-green-primary",
      secondary: "active:bg-light-green-tertiary",
      tertiary: "active:bg-light-green-tertiary",
      quaternary: "active:bg-light-green-quaternary",
      quinary: "active:bg-light-green-quinary",
    },
    focus: {
      primary: "focus:bg-light-green-primary",
      secondary: "focus:bg-light-green-tertiary",
      tertiary: "focus:bg-light-green-tertiary",
      quaternary: "focus:bg-light-green-quaternary",
      quinary: "focus:bg-light-green-quinary",
    },
    hover: {
      primary: "hover:bg-light-green-primary",
      secondary: "hover:bg-light-green-tertiary",
      tertiary: "hover:bg-light-green-tertiary",
      quaternary: "hover:bg-light-green-quaternary",
      quinary: "hover:bg-light-green-quinary",
    },
  },
  "light-blue": {
    primary: "bg-light-blue-primary",
    secondary: "bg-light-blue-tertiary",
    tertiary: "bg-light-blue-tertiary",
    quaternary: "bg-light-blue-quaternary",
    quinary: "bg-light-blue-quinary",
    active: {
      primary: "active:bg-light-blue-primary",
      secondary: "active:bg-light-blue-tertiary",
      tertiary: "active:bg-light-blue-tertiary",
      quaternary: "active:bg-light-blue-quaternary",
      quinary: "active:bg-light-blue-quinary",
    },
    focus: {
      primary: "focus:bg-light-blue-primary",
      secondary: "focus:bg-light-blue-tertiary",
      tertiary: "focus:bg-light-blue-tertiary",
      quaternary: "focus:bg-light-blue-quaternary",
      quinary: "focus:bg-light-blue-quinary",
    },
    hover: {
      primary: "hover:bg-light-blue-primary",
      secondary: "hover:bg-light-blue-tertiary",
      tertiary: "hover:bg-light-blue-tertiary",
      quaternary: "hover:bg-light-blue-quaternary",
      quinary: "hover:bg-light-blue-quinary",
    },
  },
  "light-pink": {
    primary: "bg-light-pink-primary",
    secondary: "bg-light-pink-tertiary",
    tertiary: "bg-light-pink-tertiary",
    quaternary: "bg-light-pink-quaternary",
    quinary: "bg-light-pink-quinary",
    active: {
      primary: "active:bg-light-pink-primary",
      secondary: "active:bg-light-pink-tertiary",
      tertiary: "active:bg-light-pink-tertiary",
      quaternary: "active:bg-light-pink-quaternary",
      quinary: "active:bg-light-pink-quinary",
    },
    focus: {
      primary: "focus:bg-light-pink-primary",
      secondary: "focus:bg-light-pink-tertiary",
      tertiary: "focus:bg-light-pink-tertiary",
      quaternary: "focus:bg-light-pink-quaternary",
      quinary: "focus:bg-light-pink-quinary",
    },
    hover: {
      primary: "hover:bg-light-pink-primary",
      secondary: "hover:bg-light-pink-tertiary",
      tertiary: "hover:bg-light-pink-tertiary",
      quaternary: "hover:bg-light-pink-quaternary",
      quinary: "hover:bg-light-pink-quinary",
    },
  },
  "dark-blue": {
    primary: "bg-dark-blue-primary",
    secondary: "bg-dark-blue-tertiary",
    tertiary: "bg-dark-blue-tertiary",
    quaternary: "bg-dark-blue-quaternary",
    quinary: "bg-dark-blue-quinary",
    active: {
      primary: "active:bg-dark-blue-primary",
      secondary: "active:bg-dark-blue-tertiary",
      tertiary: "active:bg-dark-blue-tertiary",
      quaternary: "active:bg-dark-blue-quaternary",
      quinary: "active:bg-dark-blue-quinary",
    },
    focus: {
      primary: "focus:bg-dark-blue-primary",
      secondary: "focus:bg-dark-blue-tertiary",
      tertiary: "focus:bg-dark-blue-tertiary",
      quaternary: "focus:bg-dark-blue-quaternary",
      quinary: "focus:bg-dark-blue-quinary",
    },
    hover: {
      primary: "hover:bg-dark-blue-primary",
      secondary: "hover:bg-dark-blue-tertiary",
      tertiary: "hover:bg-dark-blue-tertiary",
      quaternary: "hover:bg-dark-blue-quaternary",
      quinary: "hover:bg-dark-blue-quinary",
    },
  },
  "dark-red": {
    primary: "bg-dark-red-primary",
    secondary: "bg-dark-red-tertiary",
    tertiary: "bg-dark-red-tertiary",
    quaternary: "bg-dark-red-quaternary",
    quinary: "bg-dark-red-quinary",
    active: {
      primary: "active:bg-dark-red-primary",
      secondary: "active:bg-dark-red-tertiary",
      tertiary: "active:bg-dark-red-tertiary",
      quaternary: "active:bg-dark-red-quaternary",
      quinary: "active:bg-dark-red-quinary",
    },
    focus: {
      primary: "focus:bg-dark-red-primary",
      secondary: "focus:bg-dark-red-tertiary",
      tertiary: "focus:bg-dark-red-tertiary",
      quaternary: "focus:bg-dark-red-quaternary",
      quinary: "focus:bg-dark-red-quinary",
    },
    hover: {
      primary: "hover:bg-dark-red-primary",
      secondary: "hover:bg-dark-red-tertiary",
      tertiary: "hover:bg-dark-red-tertiary",
      quaternary: "hover:bg-dark-red-quaternary",
      quinary: "hover:bg-dark-red-quinary",
    },
  },
  "dark-green": {
    primary: "bg-dark-green-primary",
    secondary: "bg-dark-green-tertiary",
    tertiary: "bg-dark-green-tertiary",
    quaternary: "bg-dark-green-quaternary",
    quinary: "bg-dark-green-quinary",
    active: {
      primary: "active:bg-dark-green-primary",
      secondary: "active:bg-dark-green-tertiary",
      tertiary: "active:bg-dark-green-tertiary",
      quaternary: "active:bg-dark-green-quaternary",
      quinary: "active:bg-dark-green-quinary",
    },
    focus: {
      primary: "focus:bg-dark-green-primary",
      secondary: "focus:bg-dark-green-tertiary",
      tertiary: "focus:bg-dark-green-tertiary",
      quaternary: "focus:bg-dark-green-quaternary",
      quinary: "focus:bg-dark-green-quinary",
    },
    hover: {
      primary: "hover:bg-dark-green-primary",
      secondary: "hover:bg-dark-green-tertiary",
      tertiary: "hover:bg-dark-green-tertiary",
      quaternary: "hover:bg-dark-green-quaternary",
      quinary: "hover:bg-dark-green-quinary",
    },
  },
  "dark-pupple": {
    primary: "bg-dark-pupple-primary",
    secondary: "bg-dark-pupple-tertiary",
    tertiary: "bg-dark-pupple-tertiary",
    quaternary: "bg-dark-pupple-quaternary",
    quinary: "bg-dark-pupple-quinary",
    active: {
      primary: "active:bg-dark-pupple-primary",
      secondary: "active:bg-dark-pupple-tertiary",
      tertiary: "active:bg-dark-pupple-tertiary",
      quaternary: "active:bg-dark-pupple-quaternary",
      quinary: "active:bg-dark-pupple-quinary",
    },
    focus: {
      primary: "focus:bg-dark-pupple-primary",
      secondary: "focus:bg-dark-pupple-tertiary",
      tertiary: "focus:bg-dark-pupple-tertiary",
      quaternary: "focus:bg-dark-pupple-quaternary",
      quinary: "focus:bg-dark-pupple-quinary",
    },
    hover: {
      primary: "hover:bg-dark-pupple-primary",
      secondary: "hover:bg-dark-pupple-tertiary",
      tertiary: "hover:bg-dark-pupple-tertiary",
      quaternary: "hover:bg-dark-pupple-quaternary",
      quinary: "hover:bg-dark-pupple-quinary",
    },
  },
  "dark-gold": {
    primary: "bg-dark-gold-primary",
    secondary: "bg-dark-gold-tertiary",
    tertiary: "bg-dark-gold-tertiary",
    quaternary: "bg-dark-gold-quaternary",
    quinary: "bg-dark-gold-quinary",
    active: {
      primary: "active:bg-dark-gold-primary",
      secondary: "active:bg-dark-gold-tertiary",
      tertiary: "active:bg-dark-gold-tertiary",
      quaternary: "active:bg-dark-gold-quaternary",
      quinary: "active:bg-dark-gold-quinary",
    },
    focus: {
      primary: "focus:bg-dark-gold-primary",
      secondary: "focus:bg-dark-gold-tertiary",
      tertiary: "focus:bg-dark-gold-tertiary",
      quaternary: "focus:bg-dark-gold-quaternary",
      quinary: "focus:bg-dark-gold-quinary",
    },
    hover: {
      primary: "hover:bg-dark-gold-primary",
      secondary: "hover:bg-dark-gold-tertiary",
      tertiary: "hover:bg-dark-gold-tertiary",
      quaternary: "hover:bg-dark-gold-quaternary",
      quinary: "hover:bg-dark-gold-quinary",
    },
  },
  default: {
    primary: "bg-default-primary",
    secondary: "bg-default-tertiary",
    tertiary: "bg-default-tertiary",
    quaternary: "bg-default-quaternary",
    quinary: "bg-default-quinary",
    active: {
      primary: "active:bg-default-primary",
      secondary: "active:bg-default-tertiary",
      tertiary: "active:bg-default-tertiary",
      quaternary: "active:bg-default-quaternary",
      quinary: "active:bg-default-quinary",
    },
    focus: {
      primary: "focus:bg-default-primary",
      secondary: "focus:bg-default-tertiary",
      tertiary: "focus:bg-default-tertiary",
      quaternary: "focus:bg-default-quaternary",
      quinary: "focus:bg-default-quinary",
    },
    hover: {
      primary: "hover:bg-default-primary",
      secondary: "hover:bg-default-tertiary",
      tertiary: "hover:bg-default-tertiary",
      quaternary: "hover:bg-default-quaternary",
      quinary: "hover:bg-default-quinary",
    },
  },
};
export default themeBgColorMap;
