import { IReturnThemeColors } from "../interfaces";

const defaultThemeColors: IReturnThemeColors = {
  bg: {
    primary: "",
    secondary: "",
    tertiary: "",
    quaternary: "",
    quinary: "",
    hover: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    active: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    focus: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
  },
  text: {
    primary: "",
    secondary: "",
    tertiary: "",
    quaternary: "",
    quinary: "",
    hover: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    active: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    focus: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
  },
  border: {
    primary: "",
    secondary: "",
    tertiary: "",
    quaternary: "",
    quinary: "",
    hover: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    active: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    focus: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
  },
  shadow: {
    primary: "",
    secondary: "",
    tertiary: "",
    quaternary: "",
    quinary: "",
    hover: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    active: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
    focus: {
      primary: "",
      secondary: "",
      tertiary: "",
      quaternary: "",
      quinary: "",
    },
  },
};
export default defaultThemeColors;
