import { ThemeCodeType } from "../interfaces";

const themeBorderColorMap: ThemeCodeType = {
  "light-red": {
    primary: "border-light-red-primary",
    secondary: "border-light-red-tertiary",
    tertiary: "border-light-red-tertiary",
    quaternary: "border-light-red-quaternary",
    quinary: "border-light-red-quinary",
    active: {
      primary: "active:border-light-red-primary",
      secondary: "active:border-light-red-tertiary",
      tertiary: "active:border-light-red-tertiary",
      quaternary: "active:border-light-red-quaternary",
      quinary: "active:border-light-red-quinary",
    },
    focus: {
      primary: "focus:border-light-red-primary",
      secondary: "focus:border-light-red-tertiary",
      tertiary: "focus:border-light-red-tertiary",
      quaternary: "focus:border-light-red-quaternary",
      quinary: "focus:border-light-red-quinary",
    },
    hover: {
      primary: "hover:border-light-red-primary",
      secondary: "hover:border-light-red-tertiary",
      tertiary: "hover:border-light-red-tertiary",
      quaternary: "hover:border-light-red-quaternary",
      quinary: "hover:border-light-red-quinary",
    },
  },
  "light-green": {
    primary: "border-light-green-primary",
    secondary: "border-light-green-tertiary",
    tertiary: "border-light-green-tertiary",
    quaternary: "border-light-green-quaternary",
    quinary: "border-light-green-quinary",
    active: {
      primary: "active:border-light-green-primary",
      secondary: "active:border-light-green-tertiary",
      tertiary: "active:border-light-green-tertiary",
      quaternary: "active:border-light-green-quaternary",
      quinary: "active:border-light-green-quinary",
    },
    focus: {
      primary: "focus:border-light-green-primary",
      secondary: "focus:border-light-green-tertiary",
      tertiary: "focus:border-light-green-tertiary",
      quaternary: "focus:border-light-green-quaternary",
      quinary: "focus:border-light-green-quinary",
    },
    hover: {
      primary: "hover:border-light-green-primary",
      secondary: "hover:border-light-green-tertiary",
      tertiary: "hover:border-light-green-tertiary",
      quaternary: "hover:border-light-green-quaternary",
      quinary: "hover:border-light-green-quinary",
    },
  },
  "light-blue": {
    primary: "border-light-blue-primary",
    secondary: "border-light-blue-tertiary",
    tertiary: "border-light-blue-tertiary",
    quaternary: "border-light-blue-quaternary",
    quinary: "border-light-blue-quinary",
    active: {
      primary: "active:border-light-blue-primary",
      secondary: "active:border-light-blue-tertiary",
      tertiary: "active:border-light-blue-tertiary",
      quaternary: "active:border-light-blue-quaternary",
      quinary: "active:border-light-blue-quinary",
    },
    focus: {
      primary: "focus:border-light-blue-primary",
      secondary: "focus:border-light-blue-tertiary",
      tertiary: "focus:border-light-blue-tertiary",
      quaternary: "focus:border-light-blue-quaternary",
      quinary: "focus:border-light-blue-quinary",
    },
    hover: {
      primary: "hover:border-light-blue-primary",
      secondary: "hover:border-light-blue-tertiary",
      tertiary: "hover:border-light-blue-tertiary",
      quaternary: "hover:border-light-blue-quaternary",
      quinary: "hover:border-light-blue-quinary",
    },
  },
  "light-pink": {
    primary: "border-light-pink-primary",
    secondary: "border-light-pink-tertiary",
    tertiary: "border-light-pink-tertiary",
    quaternary: "border-light-pink-quaternary",
    quinary: "border-light-pink-quinary",
    active: {
      primary: "active:border-light-pink-primary",
      secondary: "active:border-light-pink-tertiary",
      tertiary: "active:border-light-pink-tertiary",
      quaternary: "active:border-light-pink-quaternary",
      quinary: "active:border-light-pink-quinary",
    },
    focus: {
      primary: "focus:border-light-pink-primary",
      secondary: "focus:border-light-pink-tertiary",
      tertiary: "focus:border-light-pink-tertiary",
      quaternary: "focus:border-light-pink-quaternary",
      quinary: "focus:border-light-pink-quinary",
    },
    hover: {
      primary: "hover:border-light-pink-primary",
      secondary: "hover:border-light-pink-tertiary",
      tertiary: "hover:border-light-pink-tertiary",
      quaternary: "hover:border-light-pink-quaternary",
      quinary: "hover:border-light-pink-quinary",
    },
  },
  "dark-blue": {
    primary: "border-dark-blue-primary",
    secondary: "border-dark-blue-tertiary",
    tertiary: "border-dark-blue-tertiary",
    quaternary: "border-dark-blue-quaternary",
    quinary: "border-dark-blue-quinary",
    active: {
      primary: "active:border-dark-blue-primary",
      secondary: "active:border-dark-blue-tertiary",
      tertiary: "active:border-dark-blue-tertiary",
      quaternary: "active:border-dark-blue-quaternary",
      quinary: "active:border-dark-blue-quinary",
    },
    focus: {
      primary: "focus:border-dark-blue-primary",
      secondary: "focus:border-dark-blue-tertiary",
      tertiary: "focus:border-dark-blue-tertiary",
      quaternary: "focus:border-dark-blue-quaternary",
      quinary: "focus:border-dark-blue-quinary",
    },
    hover: {
      primary: "hover:border-dark-blue-primary",
      secondary: "hover:border-dark-blue-tertiary",
      tertiary: "hover:border-dark-blue-tertiary",
      quaternary: "hover:border-dark-blue-quaternary",
      quinary: "hover:border-dark-blue-quinary",
    },
  },
  "dark-red": {
    primary: "border-dark-red-primary",
    secondary: "border-dark-red-tertiary",
    tertiary: "border-dark-red-tertiary",
    quaternary: "border-dark-red-quaternary",
    quinary: "border-dark-red-quinary",
    active: {
      primary: "active:border-dark-red-primary",
      secondary: "active:border-dark-red-tertiary",
      tertiary: "active:border-dark-red-tertiary",
      quaternary: "active:border-dark-red-quaternary",
      quinary: "active:border-dark-red-quinary",
    },
    focus: {
      primary: "focus:border-dark-red-primary",
      secondary: "focus:border-dark-red-tertiary",
      tertiary: "focus:border-dark-red-tertiary",
      quaternary: "focus:border-dark-red-quaternary",
      quinary: "focus:border-dark-red-quinary",
    },
    hover: {
      primary: "hover:border-dark-red-primary",
      secondary: "hover:border-dark-red-tertiary",
      tertiary: "hover:border-dark-red-tertiary",
      quaternary: "hover:border-dark-red-quaternary",
      quinary: "hover:border-dark-red-quinary",
    },
  },
  "dark-green": {
    primary: "border-dark-green-primary",
    secondary: "border-dark-green-tertiary",
    tertiary: "border-dark-green-tertiary",
    quaternary: "border-dark-green-quaternary",
    quinary: "border-dark-green-quinary",
    active: {
      primary: "active:border-dark-green-primary",
      secondary: "active:border-dark-green-tertiary",
      tertiary: "active:border-dark-green-tertiary",
      quaternary: "active:border-dark-green-quaternary",
      quinary: "active:border-dark-green-quinary",
    },
    focus: {
      primary: "focus:border-dark-green-primary",
      secondary: "focus:border-dark-green-tertiary",
      tertiary: "focus:border-dark-green-tertiary",
      quaternary: "focus:border-dark-green-quaternary",
      quinary: "focus:border-dark-green-quinary",
    },
    hover: {
      primary: "hover:border-dark-green-primary",
      secondary: "hover:border-dark-green-tertiary",
      tertiary: "hover:border-dark-green-tertiary",
      quaternary: "hover:border-dark-green-quaternary",
      quinary: "hover:border-dark-green-quinary",
    },
  },
  "dark-pupple": {
    primary: "border-dark-pupple-primary",
    secondary: "border-dark-pupple-tertiary",
    tertiary: "border-dark-pupple-tertiary",
    quaternary: "border-dark-pupple-quaternary",
    quinary: "border-dark-pupple-quinary",
    active: {
      primary: "active:border-dark-pupple-primary",
      secondary: "active:border-dark-pupple-tertiary",
      tertiary: "active:border-dark-pupple-tertiary",
      quaternary: "active:border-dark-pupple-quaternary",
      quinary: "active:border-dark-pupple-quinary",
    },
    focus: {
      primary: "focus:border-dark-pupple-primary",
      secondary: "focus:border-dark-pupple-tertiary",
      tertiary: "focus:border-dark-pupple-tertiary",
      quaternary: "focus:border-dark-pupple-quaternary",
      quinary: "focus:border-dark-pupple-quinary",
    },
    hover: {
      primary: "hover:border-dark-pupple-primary",
      secondary: "hover:border-dark-pupple-tertiary",
      tertiary: "hover:border-dark-pupple-tertiary",
      quaternary: "hover:border-dark-pupple-quaternary",
      quinary: "hover:border-dark-pupple-quinary",
    },
  },
  "dark-gold": {
    primary: "border-dark-gold-primary",
    secondary: "border-dark-gold-tertiary",
    tertiary: "border-dark-gold-tertiary",
    quaternary: "border-dark-gold-quaternary",
    quinary: "border-dark-gold-quinary",
    active: {
      primary: "active:border-dark-gold-primary",
      secondary: "active:border-dark-gold-tertiary",
      tertiary: "active:border-dark-gold-tertiary",
      quaternary: "active:border-dark-gold-quaternary",
      quinary: "active:border-dark-gold-quinary",
    },
    focus: {
      primary: "focus:border-dark-gold-primary",
      secondary: "focus:border-dark-gold-tertiary",
      tertiary: "focus:border-dark-gold-tertiary",
      quaternary: "focus:border-dark-gold-quaternary",
      quinary: "focus:border-dark-gold-quinary",
    },
    hover: {
      primary: "hover:border-dark-gold-primary",
      secondary: "hover:border-dark-gold-tertiary",
      tertiary: "hover:border-dark-gold-tertiary",
      quaternary: "hover:border-dark-gold-quaternary",
      quinary: "hover:border-dark-gold-quinary",
    },
  },
  default: {
    primary: "border-default-primary",
    secondary: "border-default-tertiary",
    tertiary: "border-default-tertiary",
    quaternary: "border-default-quaternary",
    quinary: "border-default-quinary",
    active: {
      primary: "active:border-default-primary",
      secondary: "active:border-default-tertiary",
      tertiary: "active:border-default-tertiary",
      quaternary: "active:border-default-quaternary",
      quinary: "active:border-default-quinary",
    },
    focus: {
      primary: "focus:border-default-primary",
      secondary: "focus:border-default-tertiary",
      tertiary: "focus:border-default-tertiary",
      quaternary: "focus:border-default-quaternary",
      quinary: "focus:border-default-quinary",
    },
    hover: {
      primary: "hover:border-default-primary",
      secondary: "hover:border-default-tertiary",
      tertiary: "hover:border-default-tertiary",
      quaternary: "hover:border-default-quaternary",
      quinary: "hover:border-default-quinary",
    },
  },
};
export default themeBorderColorMap;
