import type { Metadata } from "next";
import "./globals.css";
import RecoidContextProvider from "./recoilContextProvider";
import Navigator from "./navigator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <RecoidContextProvider>
        <body className="flex">
          <Navigator />
          {children}
        </body>
      </RecoidContextProvider>
    </html>
  );
}
