import { ThemeCodeType } from "../interfaces";

const themeTextColorMap: ThemeCodeType = {
  "light-red": {
    primary: "text-light-red-primary",
    secondary: "text-light-red-tertiary",
    tertiary: "text-light-red-tertiary",
    quaternary: "text-light-red-quaternary",
    quinary: "text-light-red-quinary",
    active: {
      primary: "active:text-light-red-primary",
      secondary: "active:text-light-red-tertiary",
      tertiary: "active:text-light-red-tertiary",
      quaternary: "active:text-light-red-quaternary",
      quinary: "active:text-light-red-quinary",
    },
    focus: {
      primary: "focus:text-light-red-primary",
      secondary: "focus:text-light-red-tertiary",
      tertiary: "focus:text-light-red-tertiary",
      quaternary: "focus:text-light-red-quaternary",
      quinary: "focus:text-light-red-quinary",
    },
    hover: {
      primary: "hover:text-light-red-primary",
      secondary: "hover:text-light-red-tertiary",
      tertiary: "hover:text-light-red-tertiary",
      quaternary: "hover:text-light-red-quaternary",
      quinary: "hover:text-light-red-quinary",
    },
  },
  "light-green": {
    primary: "text-light-green-primary",
    secondary: "text-light-green-tertiary",
    tertiary: "text-light-green-tertiary",
    quaternary: "text-light-green-quaternary",
    quinary: "text-light-green-quinary",
    active: {
      primary: "active:text-light-green-primary",
      secondary: "active:text-light-green-tertiary",
      tertiary: "active:text-light-green-tertiary",
      quaternary: "active:text-light-green-quaternary",
      quinary: "active:text-light-green-quinary",
    },
    focus: {
      primary: "focus:text-light-green-primary",
      secondary: "focus:text-light-green-tertiary",
      tertiary: "focus:text-light-green-tertiary",
      quaternary: "focus:text-light-green-quaternary",
      quinary: "focus:text-light-green-quinary",
    },
    hover: {
      primary: "hover:text-light-green-primary",
      secondary: "hover:text-light-green-tertiary",
      tertiary: "hover:text-light-green-tertiary",
      quaternary: "hover:text-light-green-quaternary",
      quinary: "hover:text-light-green-quinary",
    },
  },
  "light-blue": {
    primary: "text-light-blue-primary",
    secondary: "text-light-blue-tertiary",
    tertiary: "text-light-blue-tertiary",
    quaternary: "text-light-blue-quaternary",
    quinary: "text-light-blue-quinary",
    active: {
      primary: "active:text-light-blue-primary",
      secondary: "active:text-light-blue-tertiary",
      tertiary: "active:text-light-blue-tertiary",
      quaternary: "active:text-light-blue-quaternary",
      quinary: "active:text-light-blue-quinary",
    },
    focus: {
      primary: "focus:text-light-blue-primary",
      secondary: "focus:text-light-blue-tertiary",
      tertiary: "focus:text-light-blue-tertiary",
      quaternary: "focus:text-light-blue-quaternary",
      quinary: "focus:text-light-blue-quinary",
    },
    hover: {
      primary: "hover:text-light-blue-primary",
      secondary: "hover:text-light-blue-tertiary",
      tertiary: "hover:text-light-blue-tertiary",
      quaternary: "hover:text-light-blue-quaternary",
      quinary: "hover:text-light-blue-quinary",
    },
  },
  "light-pink": {
    primary: "text-light-pink-primary",
    secondary: "text-light-pink-tertiary",
    tertiary: "text-light-pink-tertiary",
    quaternary: "text-light-pink-quaternary",
    quinary: "text-light-pink-quinary",
    active: {
      primary: "active:text-light-pink-primary",
      secondary: "active:text-light-pink-tertiary",
      tertiary: "active:text-light-pink-tertiary",
      quaternary: "active:text-light-pink-quaternary",
      quinary: "active:text-light-pink-quinary",
    },
    focus: {
      primary: "focus:text-light-pink-primary",
      secondary: "focus:text-light-pink-tertiary",
      tertiary: "focus:text-light-pink-tertiary",
      quaternary: "focus:text-light-pink-quaternary",
      quinary: "focus:text-light-pink-quinary",
    },
    hover: {
      primary: "hover:text-light-pink-primary",
      secondary: "hover:text-light-pink-tertiary",
      tertiary: "hover:text-light-pink-tertiary",
      quaternary: "hover:text-light-pink-quaternary",
      quinary: "hover:text-light-pink-quinary",
    },
  },
  "dark-blue": {
    primary: "text-dark-blue-primary",
    secondary: "text-dark-blue-tertiary",
    tertiary: "text-dark-blue-tertiary",
    quaternary: "text-dark-blue-quaternary",
    quinary: "text-dark-blue-quinary",
    active: {
      primary: "active:text-dark-blue-primary",
      secondary: "active:text-dark-blue-tertiary",
      tertiary: "active:text-dark-blue-tertiary",
      quaternary: "active:text-dark-blue-quaternary",
      quinary: "active:text-dark-blue-quinary",
    },
    focus: {
      primary: "focus:text-dark-blue-primary",
      secondary: "focus:text-dark-blue-tertiary",
      tertiary: "focus:text-dark-blue-tertiary",
      quaternary: "focus:text-dark-blue-quaternary",
      quinary: "focus:text-dark-blue-quinary",
    },
    hover: {
      primary: "hover:text-dark-blue-primary",
      secondary: "hover:text-dark-blue-tertiary",
      tertiary: "hover:text-dark-blue-tertiary",
      quaternary: "hover:text-dark-blue-quaternary",
      quinary: "hover:text-dark-blue-quinary",
    },
  },
  "dark-red": {
    primary: "text-dark-red-primary",
    secondary: "text-dark-red-tertiary",
    tertiary: "text-dark-red-tertiary",
    quaternary: "text-dark-red-quaternary",
    quinary: "text-dark-red-quinary",
    active: {
      primary: "active:text-dark-red-primary",
      secondary: "active:text-dark-red-tertiary",
      tertiary: "active:text-dark-red-tertiary",
      quaternary: "active:text-dark-red-quaternary",
      quinary: "active:text-dark-red-quinary",
    },
    focus: {
      primary: "focus:text-dark-red-primary",
      secondary: "focus:text-dark-red-tertiary",
      tertiary: "focus:text-dark-red-tertiary",
      quaternary: "focus:text-dark-red-quaternary",
      quinary: "focus:text-dark-red-quinary",
    },
    hover: {
      primary: "hover:text-dark-red-primary",
      secondary: "hover:text-dark-red-tertiary",
      tertiary: "hover:text-dark-red-tertiary",
      quaternary: "hover:text-dark-red-quaternary",
      quinary: "hover:text-dark-red-quinary",
    },
  },
  "dark-green": {
    primary: "text-dark-green-primary",
    secondary: "text-dark-green-tertiary",
    tertiary: "text-dark-green-tertiary",
    quaternary: "text-dark-green-quaternary",
    quinary: "text-dark-green-quinary",
    active: {
      primary: "active:text-dark-green-primary",
      secondary: "active:text-dark-green-tertiary",
      tertiary: "active:text-dark-green-tertiary",
      quaternary: "active:text-dark-green-quaternary",
      quinary: "active:text-dark-green-quinary",
    },
    focus: {
      primary: "focus:text-dark-green-primary",
      secondary: "focus:text-dark-green-tertiary",
      tertiary: "focus:text-dark-green-tertiary",
      quaternary: "focus:text-dark-green-quaternary",
      quinary: "focus:text-dark-green-quinary",
    },
    hover: {
      primary: "hover:text-dark-green-primary",
      secondary: "hover:text-dark-green-tertiary",
      tertiary: "hover:text-dark-green-tertiary",
      quaternary: "hover:text-dark-green-quaternary",
      quinary: "hover:text-dark-green-quinary",
    },
  },
  "dark-pupple": {
    primary: "text-dark-pupple-primary",
    secondary: "text-dark-pupple-tertiary",
    tertiary: "text-dark-pupple-tertiary",
    quaternary: "text-dark-pupple-quaternary",
    quinary: "text-dark-pupple-quinary",
    active: {
      primary: "active:text-dark-pupple-primary",
      secondary: "active:text-dark-pupple-tertiary",
      tertiary: "active:text-dark-pupple-tertiary",
      quaternary: "active:text-dark-pupple-quaternary",
      quinary: "active:text-dark-pupple-quinary",
    },
    focus: {
      primary: "focus:text-dark-pupple-primary",
      secondary: "focus:text-dark-pupple-tertiary",
      tertiary: "focus:text-dark-pupple-tertiary",
      quaternary: "focus:text-dark-pupple-quaternary",
      quinary: "focus:text-dark-pupple-quinary",
    },
    hover: {
      primary: "hover:text-dark-pupple-primary",
      secondary: "hover:text-dark-pupple-tertiary",
      tertiary: "hover:text-dark-pupple-tertiary",
      quaternary: "hover:text-dark-pupple-quaternary",
      quinary: "hover:text-dark-pupple-quinary",
    },
  },
  "dark-gold": {
    primary: "text-dark-gold-primary",
    secondary: "text-dark-gold-tertiary",
    tertiary: "text-dark-gold-tertiary",
    quaternary: "text-dark-gold-quaternary",
    quinary: "text-dark-gold-quinary",
    active: {
      primary: "active:text-dark-gold-primary",
      secondary: "active:text-dark-gold-tertiary",
      tertiary: "active:text-dark-gold-tertiary",
      quaternary: "active:text-dark-gold-quaternary",
      quinary: "active:text-dark-gold-quinary",
    },
    focus: {
      primary: "focus:text-dark-gold-primary",
      secondary: "focus:text-dark-gold-tertiary",
      tertiary: "focus:text-dark-gold-tertiary",
      quaternary: "focus:text-dark-gold-quaternary",
      quinary: "focus:text-dark-gold-quinary",
    },
    hover: {
      primary: "hover:text-dark-gold-primary",
      secondary: "hover:text-dark-gold-tertiary",
      tertiary: "hover:text-dark-gold-tertiary",
      quaternary: "hover:text-dark-gold-quaternary",
      quinary: "hover:text-dark-gold-quinary",
    },
  },
  default: {
    primary: "text-default-primary",
    secondary: "text-default-tertiary",
    tertiary: "text-default-tertiary",
    quaternary: "text-default-quaternary",
    quinary: "text-default-quinary",
    active: {
      primary: "active:text-default-primary",
      secondary: "active:text-default-tertiary",
      tertiary: "active:text-default-tertiary",
      quaternary: "active:text-default-quaternary",
      quinary: "active:text-default-quinary",
    },
    focus: {
      primary: "focus:text-default-primary",
      secondary: "focus:text-default-tertiary",
      tertiary: "focus:text-default-tertiary",
      quaternary: "focus:text-default-quaternary",
      quinary: "focus:text-default-quinary",
    },
    hover: {
      primary: "hover:text-default-primary",
      secondary: "hover:text-default-tertiary",
      tertiary: "hover:text-default-tertiary",
      quaternary: "hover:text-default-quaternary",
      quinary: "hover:text-default-quinary",
    },
  },
};

export default themeTextColorMap;
