import { ThemeCodeType } from "../interfaces";

const themeShadowColorMap: ThemeCodeType = {
  "light-red": {
    primary: "shadow-light-red-primary",
    secondary: "shadow-light-red-tertiary",
    tertiary: "shadow-light-red-tertiary",
    quaternary: "shadow-light-red-quaternary",
    quinary: "shadow-light-red-quinary",
    active: {
      primary: "active:shadow-light-red-primary",
      secondary: "active:shadow-light-red-tertiary",
      tertiary: "active:shadow-light-red-tertiary",
      quaternary: "active:shadow-light-red-quaternary",
      quinary: "active:shadow-light-red-quinary",
    },
    focus: {
      primary: "focus:shadow-light-red-primary",
      secondary: "focus:shadow-light-red-tertiary",
      tertiary: "focus:shadow-light-red-tertiary",
      quaternary: "focus:shadow-light-red-quaternary",
      quinary: "focus:shadow-light-red-quinary",
    },
    hover: {
      primary: "hover:shadow-light-red-primary",
      secondary: "hover:shadow-light-red-tertiary",
      tertiary: "hover:shadow-light-red-tertiary",
      quaternary: "hover:shadow-light-red-quaternary",
      quinary: "hover:shadow-light-red-quinary",
    },
  },
  "light-green": {
    primary: "shadow-light-green-primary",
    secondary: "shadow-light-green-tertiary",
    tertiary: "shadow-light-green-tertiary",
    quaternary: "shadow-light-green-quaternary",
    quinary: "shadow-light-green-quinary",
    active: {
      primary: "active:shadow-light-green-primary",
      secondary: "active:shadow-light-green-tertiary",
      tertiary: "active:shadow-light-green-tertiary",
      quaternary: "active:shadow-light-green-quaternary",
      quinary: "active:shadow-light-green-quinary",
    },
    focus: {
      primary: "focus:shadow-light-green-primary",
      secondary: "focus:shadow-light-green-tertiary",
      tertiary: "focus:shadow-light-green-tertiary",
      quaternary: "focus:shadow-light-green-quaternary",
      quinary: "focus:shadow-light-green-quinary",
    },
    hover: {
      primary: "hover:shadow-light-green-primary",
      secondary: "hover:shadow-light-green-tertiary",
      tertiary: "hover:shadow-light-green-tertiary",
      quaternary: "hover:shadow-light-green-quaternary",
      quinary: "hover:shadow-light-green-quinary",
    },
  },
  "light-blue": {
    primary: "shadow-light-blue-primary",
    secondary: "shadow-light-blue-tertiary",
    tertiary: "shadow-light-blue-tertiary",
    quaternary: "shadow-light-blue-quaternary",
    quinary: "shadow-light-blue-quinary",
    active: {
      primary: "active:shadow-light-blue-primary",
      secondary: "active:shadow-light-blue-tertiary",
      tertiary: "active:shadow-light-blue-tertiary",
      quaternary: "active:shadow-light-blue-quaternary",
      quinary: "active:shadow-light-blue-quinary",
    },
    focus: {
      primary: "focus:shadow-light-blue-primary",
      secondary: "focus:shadow-light-blue-tertiary",
      tertiary: "focus:shadow-light-blue-tertiary",
      quaternary: "focus:shadow-light-blue-quaternary",
      quinary: "focus:shadow-light-blue-quinary",
    },
    hover: {
      primary: "hover:shadow-light-blue-primary",
      secondary: "hover:shadow-light-blue-tertiary",
      tertiary: "hover:shadow-light-blue-tertiary",
      quaternary: "hover:shadow-light-blue-quaternary",
      quinary: "hover:shadow-light-blue-quinary",
    },
  },
  "light-pink": {
    primary: "shadow-light-pink-primary",
    secondary: "shadow-light-pink-tertiary",
    tertiary: "shadow-light-pink-tertiary",
    quaternary: "shadow-light-pink-quaternary",
    quinary: "shadow-light-pink-quinary",
    active: {
      primary: "active:shadow-light-pink-primary",
      secondary: "active:shadow-light-pink-tertiary",
      tertiary: "active:shadow-light-pink-tertiary",
      quaternary: "active:shadow-light-pink-quaternary",
      quinary: "active:shadow-light-pink-quinary",
    },
    focus: {
      primary: "focus:shadow-light-pink-primary",
      secondary: "focus:shadow-light-pink-tertiary",
      tertiary: "focus:shadow-light-pink-tertiary",
      quaternary: "focus:shadow-light-pink-quaternary",
      quinary: "focus:shadow-light-pink-quinary",
    },
    hover: {
      primary: "hover:shadow-light-pink-primary",
      secondary: "hover:shadow-light-pink-tertiary",
      tertiary: "hover:shadow-light-pink-tertiary",
      quaternary: "hover:shadow-light-pink-quaternary",
      quinary: "hover:shadow-light-pink-quinary",
    },
  },
  "dark-blue": {
    primary: "shadow-dark-blue-primary",
    secondary: "shadow-dark-blue-tertiary",
    tertiary: "shadow-dark-blue-tertiary",
    quaternary: "shadow-dark-blue-quaternary",
    quinary: "shadow-dark-blue-quinary",
    active: {
      primary: "active:shadow-dark-blue-primary",
      secondary: "active:shadow-dark-blue-tertiary",
      tertiary: "active:shadow-dark-blue-tertiary",
      quaternary: "active:shadow-dark-blue-quaternary",
      quinary: "active:shadow-dark-blue-quinary",
    },
    focus: {
      primary: "focus:shadow-dark-blue-primary",
      secondary: "focus:shadow-dark-blue-tertiary",
      tertiary: "focus:shadow-dark-blue-tertiary",
      quaternary: "focus:shadow-dark-blue-quaternary",
      quinary: "focus:shadow-dark-blue-quinary",
    },
    hover: {
      primary: "hover:shadow-dark-blue-primary",
      secondary: "hover:shadow-dark-blue-tertiary",
      tertiary: "hover:shadow-dark-blue-tertiary",
      quaternary: "hover:shadow-dark-blue-quaternary",
      quinary: "hover:shadow-dark-blue-quinary",
    },
  },
  "dark-red": {
    primary: "shadow-dark-red-primary",
    secondary: "shadow-dark-red-tertiary",
    tertiary: "shadow-dark-red-tertiary",
    quaternary: "shadow-dark-red-quaternary",
    quinary: "shadow-dark-red-quinary",
    active: {
      primary: "active:shadow-dark-red-primary",
      secondary: "active:shadow-dark-red-tertiary",
      tertiary: "active:shadow-dark-red-tertiary",
      quaternary: "active:shadow-dark-red-quaternary",
      quinary: "active:shadow-dark-red-quinary",
    },
    focus: {
      primary: "focus:shadow-dark-red-primary",
      secondary: "focus:shadow-dark-red-tertiary",
      tertiary: "focus:shadow-dark-red-tertiary",
      quaternary: "focus:shadow-dark-red-quaternary",
      quinary: "focus:shadow-dark-red-quinary",
    },
    hover: {
      primary: "hover:shadow-dark-red-primary",
      secondary: "hover:shadow-dark-red-tertiary",
      tertiary: "hover:shadow-dark-red-tertiary",
      quaternary: "hover:shadow-dark-red-quaternary",
      quinary: "hover:shadow-dark-red-quinary",
    },
  },
  "dark-green": {
    primary: "shadow-dark-green-primary",
    secondary: "shadow-dark-green-tertiary",
    tertiary: "shadow-dark-green-tertiary",
    quaternary: "shadow-dark-green-quaternary",
    quinary: "shadow-dark-green-quinary",
    active: {
      primary: "active:shadow-dark-green-primary",
      secondary: "active:shadow-dark-green-tertiary",
      tertiary: "active:shadow-dark-green-tertiary",
      quaternary: "active:shadow-dark-green-quaternary",
      quinary: "active:shadow-dark-green-quinary",
    },
    focus: {
      primary: "focus:shadow-dark-green-primary",
      secondary: "focus:shadow-dark-green-tertiary",
      tertiary: "focus:shadow-dark-green-tertiary",
      quaternary: "focus:shadow-dark-green-quaternary",
      quinary: "focus:shadow-dark-green-quinary",
    },
    hover: {
      primary: "hover:shadow-dark-green-primary",
      secondary: "hover:shadow-dark-green-tertiary",
      tertiary: "hover:shadow-dark-green-tertiary",
      quaternary: "hover:shadow-dark-green-quaternary",
      quinary: "hover:shadow-dark-green-quinary",
    },
  },
  "dark-pupple": {
    primary: "shadow-dark-pupple-primary",
    secondary: "shadow-dark-pupple-tertiary",
    tertiary: "shadow-dark-pupple-tertiary",
    quaternary: "shadow-dark-pupple-quaternary",
    quinary: "shadow-dark-pupple-quinary",
    active: {
      primary: "active:shadow-dark-pupple-primary",
      secondary: "active:shadow-dark-pupple-tertiary",
      tertiary: "active:shadow-dark-pupple-tertiary",
      quaternary: "active:shadow-dark-pupple-quaternary",
      quinary: "active:shadow-dark-pupple-quinary",
    },
    focus: {
      primary: "focus:shadow-dark-pupple-primary",
      secondary: "focus:shadow-dark-pupple-tertiary",
      tertiary: "focus:shadow-dark-pupple-tertiary",
      quaternary: "focus:shadow-dark-pupple-quaternary",
      quinary: "focus:shadow-dark-pupple-quinary",
    },
    hover: {
      primary: "hover:shadow-dark-pupple-primary",
      secondary: "hover:shadow-dark-pupple-tertiary",
      tertiary: "hover:shadow-dark-pupple-tertiary",
      quaternary: "hover:shadow-dark-pupple-quaternary",
      quinary: "hover:shadow-dark-pupple-quinary",
    },
  },
  "dark-gold": {
    primary: "shadow-dark-gold-primary",
    secondary: "shadow-dark-gold-tertiary",
    tertiary: "shadow-dark-gold-tertiary",
    quaternary: "shadow-dark-gold-quaternary",
    quinary: "shadow-dark-gold-quinary",
    active: {
      primary: "active:shadow-dark-gold-primary",
      secondary: "active:shadow-dark-gold-tertiary",
      tertiary: "active:shadow-dark-gold-tertiary",
      quaternary: "active:shadow-dark-gold-quaternary",
      quinary: "active:shadow-dark-gold-quinary",
    },
    focus: {
      primary: "focus:shadow-dark-gold-primary",
      secondary: "focus:shadow-dark-gold-tertiary",
      tertiary: "focus:shadow-dark-gold-tertiary",
      quaternary: "focus:shadow-dark-gold-quaternary",
      quinary: "focus:shadow-dark-gold-quinary",
    },
    hover: {
      primary: "hover:shadow-dark-gold-primary",
      secondary: "hover:shadow-dark-gold-tertiary",
      tertiary: "hover:shadow-dark-gold-tertiary",
      quaternary: "hover:shadow-dark-gold-quaternary",
      quinary: "hover:shadow-dark-gold-quinary",
    },
  },
  default: {
    primary: "shadow-default-primary",
    secondary: "shadow-default-tertiary",
    tertiary: "shadow-default-tertiary",
    quaternary: "shadow-default-quaternary",
    quinary: "shadow-default-quinary",
    active: {
      primary: "active:shadow-default-primary",
      secondary: "active:shadow-default-tertiary",
      tertiary: "active:shadow-default-tertiary",
      quaternary: "active:shadow-default-quaternary",
      quinary: "active:shadow-default-quinary",
    },
    focus: {
      primary: "focus:shadow-default-primary",
      secondary: "focus:shadow-default-tertiary",
      tertiary: "focus:shadow-default-tertiary",
      quaternary: "focus:shadow-default-quaternary",
      quinary: "focus:shadow-default-quinary",
    },
    hover: {
      primary: "hover:shadow-default-primary",
      secondary: "hover:shadow-default-tertiary",
      tertiary: "hover:shadow-default-tertiary",
      quaternary: "hover:shadow-default-quaternary",
      quinary: "hover:shadow-default-quinary",
    },
  },
};

export default themeShadowColorMap;
